### ISSUE TITLE
Release app installer package.

### ISSUE THREAD

**Issue by Jakeverse** [dotMorten/ArcGISDesktop#1]
Thanks for making this great app.

Can you please release installer file so people like me can install and use this beautiful maps app.
I really liked this  app so much. I thought you maybe release later but you have not worked in this project for a while.

If this app usable right now then please release a simple installer file, I don't have visual studio knowledge to build manually or enough internet speed to download VS. 

Please consider releasing installer if possible. 😊

**Comment by dotMorten** [comment]
Thanks for the kind words but this app is just my personal playground for experimenting with the API and WinUI. I have no intent on making this an actual useful app for people
